// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyQ6JQUW36V4d1mSZQKzBWCBXsVC86JjU',
    appId: '1:786871248294:web:57e0829d473976517f5b67',
    messagingSenderId: '786871248294',
    projectId: 'genshin-abyss-drafter',
    authDomain: 'genshin-abyss-drafter.firebaseapp.com',
    storageBucket: 'genshin-abyss-drafter.appspot.com',
    measurementId: 'G-2NNX3PEM86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEDJHDx2PH1J_6qrAn2DIu0gElewfTkQg',
    appId: '1:786871248294:android:65977a6432f3c7a97f5b67',
    messagingSenderId: '786871248294',
    projectId: 'genshin-abyss-drafter',
    storageBucket: 'genshin-abyss-drafter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTK2OcyJqkdJ4qvCooyMhPJxK_jeTxbY',
    appId: '1:786871248294:ios:bc9721946e15b8747f5b67',
    messagingSenderId: '786871248294',
    projectId: 'genshin-abyss-drafter',
    storageBucket: 'genshin-abyss-drafter.appspot.com',
    iosClientId: '786871248294-t3mk9mffjm6manj3jlsf80lblols0vg6.apps.googleusercontent.com',
    iosBundleId: 'com.fdthai.genshinAbyssDrafter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuTK2OcyJqkdJ4qvCooyMhPJxK_jeTxbY',
    appId: '1:786871248294:ios:bc9721946e15b8747f5b67',
    messagingSenderId: '786871248294',
    projectId: 'genshin-abyss-drafter',
    storageBucket: 'genshin-abyss-drafter.appspot.com',
    iosClientId: '786871248294-t3mk9mffjm6manj3jlsf80lblols0vg6.apps.googleusercontent.com',
    iosBundleId: 'com.fdthai.genshinAbyssDrafter',
  );
}
